import { join } from 'node:path';

const serverDir  = join(import.meta.dir, '..');
const overlayDir = join(serverDir, 'overlay');
const transpiler = new Bun.Transpiler({ loader: 'ts' });

const WIDGETS   = ['lot', 'price', 'timer', 'bids', 'top-bid', 'winner'];
const HTML_NAMES = ['index', ...WIDGETS];
const CSS_NAMES  = ['shared', 'index', ...WIDGETS];
const TS_NAMES   = ['shared', 'index', ...WIDGETS];

const files: Record<string, { body: string; type: string }> = {};

for (const name of HTML_NAMES) {
  const html = await Bun.file(join(overlayDir, `${name}.html`)).text();
  files[`${name}.html`] = { body: html, type: 'text/html; charset=utf-8' };
}

for (const name of CSS_NAMES) {
  const f = Bun.file(join(overlayDir, `${name}.css`));
  if (await f.exists()) {
    files[`${name}.css`] = { body: await f.text(), type: 'text/css' };
  }
}

for (const name of TS_NAMES) {
  const source = await Bun.file(join(overlayDir, `${name}.ts`)).text();
  const js     = await transpiler.transform(source);
  files[`${name}.js`] = { body: js, type: 'application/javascript' };
}

const out = `\
// AUTO-GENERATED by scripts/bundle-assets.ts — do not edit manually.
// Run: bun run bundle-assets
export const WIDGET_FILES: Record<string, { body: string; type: string }> = ${JSON.stringify(files, null, 2)};
`;

await Bun.write(join(serverDir, 'src/overlay/assets-inline.ts'), out);
console.error('[bundle-assets] src/overlay/assets-inline.ts updated');
